# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-01 11:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ambientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('codRes', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nomPerRes', models.CharField(max_length=100)),
                ('apePerRes', models.CharField(max_length=100)),
                ('dniPerRes', models.CharField(max_length=8)),
                ('nroPerRes', models.IntegerField(default=1, help_text='Debe incluir a la persona')),
                ('fecRes', models.DateTimeField()),
                ('detalle', models.TextField(blank=True, default=None, null=True)),
                ('fecCreRes', models.DateTimeField(auto_now_add=True)),
                ('fecModRes', models.DateTimeField(auto_now=True)),
                ('mesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ambientes.Mesa')),
            ],
        ),
    ]
